[package]
name = "wa-ulid"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2.14", features = ["js"] }
rand = "0.8.5"
wasm-bindgen = "0.2.92"

[profile.release]
lto = true
